### ISSUE TITLE
reflexive access

### ISSUE THREAD

**Issue by lolostar** [linkedpipes/etl#690] opened 2019-06-19 13:44 UTC
Hi,

I installed etl on a new machine and I get :

WARNING: An illegal reflective access operation has occurredTL-Frontend@1.0.0-alpha.0~prepare: LP-ETL-Frontend@1.0.0-alpha.0
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/centos/Applications/etl/deploy/executor-monitor/lib/spring-core-4.3.20.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
We have started our server on port 8080

although I changed the conf file as indicated
configuration.properties.txt

Any idea ?

Thank you,

Laurent

**Comment by jakubklimek** [comment] 2019-06-27 08:53
Hello,

does the build continue correctly? We see these warnings with the latest Java versions, but currently they should not be a problem (up to JDK 12).

**Comment by skodapetr** [comment] 2019-06-27 11:25
This is caused by an older Spring library and should be of no issue to runtime. 
In commit  6e5aa19d0ce5535e22eec2aceab6ec453f8ffd5d we updated the dependencies and fixed some compile time warnings (where possible). However, the commit is available only in develop, and it will take some time before we manage to check that nothing has been broken.

**Comment by jakubklimek** [comment] 2019-06-27 14:10
A similar warning
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
is still present at the start of compilation. @skodapetr are you sure nothing can be done about that?

**Comment by jakubklimek** [comment] 2019-06-28 05:43
The mentioned warning is in build time, whereas the original issue is from runtime. Closing, can be reopened if this causes trouble.

**Closed by jakubklimek** 2019-06-28 05:43 UTC
Labels: test
