### ISSUE TITLE
Consider wrapping pipeline fragments

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#128] opened 2016-04-29 13:49 UTC
When a pipeline fragment is imported, all its components become a part of the edited pipeline. This may expose low-level details of the fragment's implementation and overwhelm the user of the fragment. Instead, consider wrapping pipeline fragments similarly as DPU instances, so that they can be reused without users needing to care for their internals.

However, this would require the pipeline fragment designer to specify explicitly the inputs and outputs of the fragment, so that they can be exposed to the fragment's users.

**Comment by skodape** [comment] 2016-04-29 13:53
Duplicate of #32

**Closed by skodape** 2016-04-29 13:53 UTC
