### ISSUE TITLE
Enhancement: Add select box for MIME types or remove the need to provide a MIME type

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#281] opened 2017-01-07 13:00 UTC
The SPARQL endpoint component requires users to fill in the MIME type to use in content negotiation. Users need to type this in, since the type of the input is `text`. A better user experience can be achieved if the MIME types are listed in a select box.

However, it is unclear why the MIME type needs to be provided at all. Since the component provides an RDF unit the choice of the MIME type doesn't influence the output. MIME type can be automatically determined from the `Content-Type` HTTP header the queried SPARQL endpoint.

Tested with 13056e4e826cda7dcb10c2fb184ee0dfea14fd78.

**Comment by skodapetr** [comment] 2017-01-07 13:21
In some cases the default endpoint mime-type may not work properly (see #217), in such case the user may decide to choose different mime-type, which may not always match the expectations (see #217, where Virtuoso use "text/plain" for N-Triples).

However in most cases it's probably necessary to force user in filling in this field.
A solution might be to use default inheritance for core templates (inherit the value from template) or provide reasonable default to core templates (pre-fill the value).

We may provide [autocomplete](https://material.angularjs.org/latest/demo/autocomplete) with some default formats, this should be similar to the select box with custom value.

**Comment by jindrichmynarz** [comment] 2017-01-07 13:37
I found out that while the MIME field is marked as required, a pipeline without it runs just fine, so there might be a problem either in (1) the UI mistakenly marking it as required or (2) the validation not catching that it's empty.

**Comment by jakubklimek** [comment] 2017-05-27 06:51
It should not be marked as required.

**Comment by jindrichmynarz** [comment] 2017-05-29 14:23
In a6ec3bb4b6748aa6681560c85935f2a3dbca7362 the MIME type is no longer required in the UI. However, the original issue with the free-text input of the MIME type parameter is still present.

**Comment by skodapetr** [comment] 2017-05-29 14:34
@jindrichmynarz So the issue is to provide predefined set of possible options (select box) and force user to choose from them ?

**Comment by jindrichmynarz** [comment] 2017-05-29 14:39
The issue is to improve the usability of the input UI for the MIME type parameter. Since LP-ETL supports a limited set of MIME types, it would be good to support the user in figuring them out, instead of letting the user guess. For example, the support my be provided via a select box or autocomplete.

**Comment by skodapetr** [comment] 2017-05-29 14:44
@jindrichmynarz LP use RDF4J .. so we can list supported MIME types as an autocomplete, is that ok?

**Comment by jindrichmynarz** [comment] 2017-05-29 14:47
In fact, there are two kinds of supported MIME types:

1. Those that the queried SPARQL endpoint can produce.
2. Those that LP-ETL can parse.

Ideally, the MIME type input should be constrained to the intersection of MIME types in 1. and 2. This is not feasible to do statically, since the MIME types supported by the SPARQL endpoint would require additional [request to the endpoint](https://www.w3.org/TR/sparql11-service-description).

Moreover, the same payload may need a different MIME type for the SPARQL endpoint and LP-ETL. For example, while N-Triples is `text/plain` for Virtuoso, it is `text/ntriples` for LP-ETL. 

I think that a reasonable solution is what you suggest. Make this a list of MIME types supported by LP-ETL and throw an error in case the queried SPARQL endpoint returns HTTP 406 Not Acceptable. This does not solve the issue of inconsistent MIME type though.

Additionally, the MIME type parameter is [undocumented](http://etl.linkedpipes.com/components/e-sparql).

**Comment by jindrichmynarz** [comment] 2017-05-30 09:58
It seems there are duplicate options in the select box. For example, `application/x-turtle` and `text/turtle` or `application/x-nquads` and `text/nquads`. Even though these aliases might be supported by RDF4J, I think I would be better if only the [standard MIME types registered at IANA were listed](https://www.iana.org/assignments/media-types/media-types.xhtml).

**Comment by jakubklimek** [comment] 2017-05-30 10:02
These aliases are in use by preRDF 1.1 endpoints, from before the MIME types were standardized by IANA. Therefore it is useful to have them there for legacy endpoints.

**Closed by jakubklimek** 2017-05-30 10:02 UTC
Labels: enhancement, test

**Comment by jindrichmynarz** [comment] 2017-05-30 11:25
Yes, but we agreed above not to list MIME types supported by SPARQL endpoints, but instead the MIME types supported by LP-ETL (i.e. RDF4J).

**Comment by jakubklimek** [comment] 2017-05-30 11:28
True, but these are also still supported by RDF4J.

**Comment by jindrichmynarz** [comment] 2017-05-30 11:34
Sure, that was what my second comment was about. I suggested to show an intersection of standard MIME types and the MIME types supported by RDF4J.

**Comment by jakubklimek** [comment] 2017-05-30 11:38
That would break the original use case for this field, as ```text/plain``` is not a standard MIME type for RDF data, yet it is necessary for some Virtuoso instances to get the correct result.

**Comment by jindrichmynarz** [comment] 2017-05-30 11:44
`text/plain` is a standard MIME type, but not a MIME type associated with `text/ntriples`. What I think should be removed are non-standard aliases, such as `application/x-nquads` for `application/n-quads`.

**Comment by jakubklimek** [comment] 2017-05-31 08:12
OK
