### ISSUE TITLE
Unable to work with population data from DBPedia

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/etl#217] opened 2016-07-26 11:05 UTC
```
http://dbpedia.org/sparql
```

```
PREFIX dbo: <http://dbpedia.org/ontology/>
 PREFIX dbp: <http://dbpedia.org/property/>

 CONSTRUCT {
    ?p a dbo:PopulatedPlace ;
         dbo:populationTotal ?population ;
         dbp:officialName ?on .
 } WHERE {
    ?p a dbo:PopulatedPlace ;
         dbo:populationTotal ?population ;
         dbp:officialName ?on .
 }
```

**Comment by jirihelmich** [comment] 2016-07-26 11:09
http://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1469531328407&execution=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F7a3da175-f0c7-4fa0-b99a-92f179a5b9d6

**Comment by jirihelmich** [comment] 2016-07-26 11:10
```
Cause: 
Can't query remote SPARQL.

Root cause: 
RDFParseException : Expected an RDF value here, found '‘' [line 4020]
```

**Comment by skodape** [comment] 2016-07-26 13:39
Can be fixed with additional configuration, please see updated version of the pipeline.

The problem is invalid(?) character in resource IRI. Use following query to return the problematic resource:
```
PREFIX dbo: <http://dbpedia.org/ontology/>

CONSTRUCT {
  ?s a dbo:PopulatedPlace .
} WHERE {
  ?s a dbo:PopulatedPlace ;
    dbp:officialName "G\u02BBijduvon"@en .
}
```
The problem is that in turtle the resources is returned as ```dbr:G‘ijduvon```. However in case of n-triples we get ```<http://dbpedia.org/resource/G\u2018ijduvon>```.  So a quick solution is to use different format.

**Comment by jirihelmich** [comment] 2016-11-03 11:42
Does not seem to work. Any ideas?

http://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2Fcreated-1478172191456&execution=http:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F51cad3b3-9852-4247-95d4-aafc91e3247d

**Comment by skodapetr** [comment] 2016-11-03 13:38
You need to use "text/plain" as Virtuoso use this mime.-type for N-Triples.

**Closed by skodapetr** 2016-11-03 13:38 UTC
Labels: test

**Comment by jirihelmich** [comment] 2016-11-03 13:39
Isn't this very obscure? I mean which user will come up with this as a solution for being able to process data from DBPedia?

**Comment by skodapetr** [comment] 2016-11-03 13:45
It is, however it is problem of Virtuoso - invalid Turtle serialisation, or obscure use of Mime-types. 
For example for "application/n-triples" Virtuoso return Turtle - and here we are back with the problem of invalid formatting.
```
<http://dbpedia.org/resource/1931_Hawke\u0027s_Bay_earthquake>	owl:sameAs	dbpedia-de:Hawke’s-Bay-Erdbeben_von_1931 .
```

We may provide some default "Virtuoso" friendly configuration as a template or add this information to some FAQ.

**Comment by jirihelmich** [comment] 2016-11-03 13:48
I would try to come up with something as it's simply the largest and best known data source. So it does not really matter what are the specs, this is, unfortunately, the reality...

Secondly, it's weird that I had never any issues with Jena while working with DBPedia... Is this some OpenRDF x Virtuoso anxiety?

**Comment by skodapetr** [comment] 2016-11-03 14:14
Yes, it is unfortunate - perhaps the best way is to report this issue.

I also try Jena 3.1.0 to load the aforementioned statement and I got:
```
15:10:56.114 ERROR org.apache.jena.riot - [line: 3, col: 120] Failed to find a prefix name or keyword: �(8217;0x2019)
Exception in thread "main" org.apache.jena.riot.RiotException: [line: 3, col: 120] Failed to find a prefix name or keyword: �(8217;0x2019)
```
When I remove the ```’```  from subject IRI it works fine. I hope I got the code right:
```
    public static final String TURTLE = ""
            + "@prefix dbpedia-de:	<http://de.dbpedia.org/resource/> .\n"
            + "\n"
            + "<http://dbpedia.org/resource/1931_Hawke\\u0027s_Bay_earthquake>"
            + " <http://www.w3.org/2002/07/owl#sameAs>"
            + "  dbpedia-de:Hawke’s-Bay-Erdbeben_von_1931 ."
            + "";

    public static void main(String[] args) throws Exception {
        final Model model = ModelFactory.createDefaultModel() ;
        final InputStream stream = new ByteArrayInputStream(
                TURTLE.getBytes("UTF-8"));
        model.read(stream, "http://localhost/base", "TTL");
        model.write(System.out, "TTL");
    }
```

**Comment by jirihelmich** [comment] 2016-11-03 19:09
Yes, that seems right. It may be the case that Jena does not use TTL as default which would explain why I did not experience this ever.

Thanks for your help, I somehow fixed it (if url.contains(dbpedia) => add header)...

**Comment by jindrichmynarz** [comment] 2017-01-07 13:35
Both the [buggy Turtle serializer](https://github.com/openlink/virtuoso-opensource/issues/454) and [missing support for the standard `application/n-triples` header](https://github.com/openlink/virtuoso-opensource/issues/516) are known Virtuoso bugs. The work-around I used in the past, similar to what @jirihelmich describes, is to detect Virtuoso from the `Server` HTTP header and adjust the request `Accept` headers accordingly if we are dealing with Virtuoso. For example:

```bash
curl -sI http://dbpedia.org/sparql | grep ^Server
Server: Virtuoso/07.20.3217 (Linux) i686-generic-linux-glibc212-64  VDB
```

The limitation of this work-around is that it is useful mostly in the context of executing multiple queries. I usually start the connection by pinging the SPARQL endpoint with a HTTP HEAD request and obtain this info for use in further requests.
