### ISSUE TITLE
XSLT transformer adds suffix instead of replacing it

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#230] opened 2016-09-27 15:54 UTC
This is a minor enhancement.

The XSLT transformer adds a file suffix instead of replacing it. So, if you have a `file.xml` and configure the suffix to be `rdf`, then the resulting file will be named `file.xml.rdf`.

Tested on the latest develop version (781636d191c924bb781c2a5db3e62c8d8cb1f849).

**Comment by jakubklimek** [comment] 2016-09-27 18:21
This is by design, easier to track the source and target file. Is there any actual problem with this?

**Comment by jindrichmynarz** [comment] 2016-09-27 18:49
It can be confusing to users, in particular if using Files renamer component.

I don't think it has value for tracking the source and target files. Tracking is already available via the debug view.

**Comment by jakubklimek** [comment] 2016-09-27 18:53
I meant for tracking in debug view. No information is lost. It is similar as gzipping a ttl file... results in .ttl.gz instead of just .gz

**Comment by jindrichmynarz** [comment] 2016-09-27 18:56
You can see that the input is called `file.xml` and the output is called `file.rdf` in the debug view. There's no need for a component to encode the renaming into a file name such as `file.xml.rdf`, from which you can backwards reason to `file.xml`.

**Comment by jakubklimek** [comment] 2016-09-27 18:59
Yes, but the original extension is lost this way. Not all XML files have the .xml extension. E.g. RDF/XML files have the .rdf extension. So when you have file.xml and file.rdf, you get a confilct when you replace. That is why simple addition is better.

**Comment by jindrichmynarz** [comment] 2016-09-27 19:02
The original extension is not lost, because you can see it in the name of the input to the XSLT component.

Does a conflict arise when two components produce a file with the same name?

**Comment by jakubklimek** [comment] 2016-09-27 19:03
Yes, the conflict happens in the output. You would get only one file.rdf and you would not be able to tell whether it is from file.xml or file.rdf on the input.

**Comment by jindrichmynarz** [comment] 2016-09-27 19:14
I assumed each component creates files in its own directory, hence conflicts cannot arise. Is that an incorrect assumption?

**Comment by jakubklimek** [comment] 2016-09-27 19:27
That is not the point.
There is only one output directory. There, quite naturally, you cannot have 2 files with the same name.
This would happen using the replace method if you had file.rdf and file.xml on the input - both extensions would be stripped and, e.g. .rdf extension would be added to both, resulting in the same file name.

**Comment by jindrichmynarz** [comment] 2016-09-27 19:43
Only one output directory? I though components have isolated outputs to prevent clashes.

If appending file suffixes in XSLT component is primarily meant as protection against file name clashes, then it is an ad hoc one. I think either the outputs of components should be separated, so a more systematic approach to preventing clashes of file names should be adopted, since this issue may arise in any component that takes a file input and produces a file output.

**Comment by jakubklimek** [comment] 2016-09-27 19:46
One per output data unit, of course.

I simply do not see the confusion, it seems cleaner than replacing the extension and as I mentioned before, is the same in, e.g., zipping files.

**Comment by jindrichmynarz** [comment] 2016-09-27 19:55
"Per output data unit" means that all files in a pipeline must have different names?

I think now the original issue is immaterial since we discovered this much graver issue with the assumption of unique file names throughout a pipeline.

**Comment by jakubklimek** [comment] 2016-09-27 19:56
No.

Each component has its own output data units.

**Comment by jindrichmynarz** [comment] 2016-09-27 20:01
> Each component has its own output data units.

Then how can a conflict arise?

**Comment by skodape** [comment] 2016-09-28 06:46
You can have files `A.rdf` and `A.xml` on input.

**Comment by jindrichmynarz** [comment] 2016-09-28 07:47
What happens if you have `A.xml` and `A.xml` in the input?

**Comment by skodape** [comment] 2016-09-28 09:15
Well, let's imagine we have the `xml` as extension. Now you got `A.rdf.xml` and `A.xml.xml`. If the extension is replaced you would get `A.xml` - so you lost randomly one of the files. 

We could talk about a policy how to deal with this - but we should consider if that additional complexity is worthy of the extension replacement. 

Plus we need to deal with situations like `file.2016.09.01` - where the `2016.09.01` may not be an extension (by design) but we would replace this as the extension is the suffix after the last dot.

Plus if there is no extension, should we simply add it or not (as `replace('X', 'Y')` wont do nothing id 'X' is missing).

You can always follow this component with the files renamer - but it's true that in certain cases the performance cost of this, may lead us to consideration of some special option?

**Comment by jindrichmynarz** [comment] 2016-09-28 10:16
I think the original issue is now immaterial and a more important issue to solve is what happens when a component receives input with duplicate names. I think the simplest solution that can happen is to throw a descriptive error and fail the pipeline execution. Currently a random input is selected and the pipeline executes without an error.

**Comment by jakubklimek** [comment] 2016-09-28 10:18
This is a known thing. Is there any real use case where this is a problem? If not, I would close this.

**Comment by jindrichmynarz** [comment] 2016-09-28 10:27
I think the issue is that if this happens, the user won't probably notice. Maybe it already happens a bunch, but we haven't found out about it yet.

**Comment by jindrichmynarz** [comment] 2016-10-20 08:06
I found a case when the appending suffix behaviour is problematic. When you pass a reference to a file instead of a data unit, such as in the Virtuoso loader, you need to manually reconstruct the behaviour be able to provide correct file path. For example, when I have `2015.xml` as my input that is passed through two XSLTs, one producing `*.xml`, the other producing `*.rdf`, then the output name is `2015.xml.xml.rdf`.

**Comment by jakubklimek** [comment] 2016-10-20 08:14
Well, that is more of a inconvenience than a problem. You can easily fix this using http://etl.linkedpipes.com/components/t-filesrenamer

Another point to consider is that file extension is not mandatory and, in case of e.g. web service output, or XHTML page download, is typically not present at all, therefore there is nothing to replace. The append operation is therefore both simpler and safer.

**Comment by jindrichmynarz** [comment] 2016-10-20 08:55
Exactly, using the Files renamer component is what I have done. I think this is a usability issue that is easy to stumble over.

**Comment by skodapetr** [comment] 2017-03-26 07:58
@jindrichmynarz To the issue with "duplicate names". There is now check, that prevents creation of already existing file. For example, renaming two files to same name cause execution to fail. If there are two files of the same name on input they are see as "different files" (can be tested with two text holder and one RdfToSingleGraph)

**Comment by jakubklimek** [comment] 2018-04-25 08:11
To sum up, it is safer to append extensions to filenames than to try to replace them when the may not even be there. The filename duplicate issue has been addressed.

**Closed by jakubklimek** 2018-04-25 08:11 UTC
Labels: enhancement
