### ISSUE TITLE
Improve errors from command-line scripts

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#200] opened 2016-07-02 06:26 UTC
Due to the new layout of the FTP configuration `executor-monitor.sh` raises an error when run with the old configuration:

```
[main] INFO  c.l.e.e.m.Configuration - Reading configuration file: configuration.properties
[main] ERROR c.l.e.e.m.Configuration - Missing configuration property: 'executor-monitor.ftp.command_port'
Exception in thread "main" java.lang.RuntimeException: Missing configuration property!
    at com.linkedpipes.etl.executor.monitor.Configuration.getProperty(Configuration.java:178)
    at com.linkedpipes.etl.executor.monitor.Configuration.getPropertyInteger(Configuration.java:185)
    at com.linkedpipes.etl.executor.monitor.Configuration.loadProperties(Configuration.java:79)
    at com.linkedpipes.etl.executor.monitor.Configuration.init(Configuration.java:68)
    at com.linkedpipes.etl.executor.monitor.ExecutorMonitor.initLogger(ExecutorMonitor.java:92)
    at com.linkedpipes.etl.executor.monitor.ExecutorMonitor.main(ExecutorMonitor.java:107)
```

It would be more user-friendly to catch this exception, print the message `Missing configuration property: 'executor-monitor.ftp.command_port'` and `System.exit(1)`. Similar treatment (i.e. catch and exit with a friendlier error) can be applied to other situations as well.

**Comment by jakubklimek** [comment] 2016-07-02 12:54
I think the exception is descriptive enough... this situation is quite rare - only when we change something substantial - so it is not worth investing effort in right now...
The issue is therefore a generic remark that errors should ideally be handled i a user friendly way?

**Comment by jindrichmynarz** [comment] 2016-07-02 12:57
Yes, it is meant as a proposed enhancement to catch simple errors and exit gracefully, while reporting a user-friendly error message.

**Comment by jakubklimek** [comment] 2016-07-02 14:36
Sure, but I don't think we need to have an issue for this as this is low priority, there will always be some exceptions and the remark is generic, not specific to lp-etl. There are many other tools which output the whole stack trace along with the error message...

**Comment by jakubklimek** [comment] 2021-04-14 10:16
Also, the stack si better for diagnostics and debugging. I think we can close this as it is rather cosmetic.

**Closed by jakubklimek** 2021-04-14 10:16 UTC
Labels: enhancement
