### ISSUE TITLE
Vague exception for unsupported SPARQL function

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#151] opened 2016-05-18 13:32 UTC
Sesame/RDF4J used in LinkedPipes doesn't seem to support the [`RAND()` function](https://www.w3.org/TR/sparql11-query/#idp2130040). However, when a SPARQL query using `RAND()` is used, the exception raised by LP-ETL is too vague; it simply logs a NPE:

```
[SPARQL construct] ERROR c.l.e.e.a.v.e.LocalizedException - LocalizedException: Operation failed.
java.lang.NullPointerException: null
    at org.openrdf.query.algebra.evaluation.iterator.OrderIterator.createIteration(OrderIterator.java:163) ~[sesame-queryalgebra-evaluation-4.0.0.jar:na]
    at info.aduna.iteration.DelayedIteration.hasNext(DelayedIteration.java:73) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.FilterIteration.findNextElement(FilterIteration.java:79) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.FilterIteration.hasNext(FilterIteration.java:54) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.LimitIteration.hasNext(LimitIteration.java:73) ~[sesame-util-4.0.0.jar:na]
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:69) ~[sesame-queryalgebra-evaluation-4.0.0.jar:na]
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:30) ~[sesame-queryalgebra-evaluation-4.0.0.jar:na]
    at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60) ~[sesame-util-4.0.0.jar:na]
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68) ~[sesame-util-4.0.0.jar:na]
    at org.openrdf.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:100) ~[sesame-sail-base-4.0.0.jar:na]
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68) ~[sesame-util-4.0.0.jar:na]
    at org.openrdf.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:52) ~[sesame-sail-api-4.0.0.jar:na]
    at info.aduna.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:73) ~[sesame-util-4.0.0.jar:na]
    at org.openrdf.repository.sail.helpers.SailUpdateExecutor.executeModify(SailUpdateExecutor.java:506) ~[sesame-repository-sail-4.0.0.jar:na]
    at org.openrdf.repository.sail.helpers.SailUpdateExecutor.executeUpdate(SailUpdateExecutor.java:134) ~[sesame-repository-sail-4.0.0.jar:na]
    at org.openrdf.repository.sail.SailUpdate.execute(SailUpdate.java:91) ~[sesame-runtime-osgi-4.0.1-SNAPSHOT-custom.jar:na]
    at com.linkedpipes.plugin.transformer.sparql.construct.SparqlConstruct.lambda$execute$0(SparqlConstruct.java:48) [t-sparqlConstruct-0.0.0.jar:na]
    at com.linkedpipes.etl.dataunit.sesame.ActionExecutor.execute(ActionExecutor.java:24) ~[dataunit-sesame-impl-0.0.0.jar:na]
    at com.linkedpipes.etl.dataunit.sesame.SesameDataUnitImpl.execute(SesameDataUnitImpl.java:61) [dataunit-sesame-impl-0.0.0.jar:na]
    at com.linkedpipes.etl.dataunit.sesame.SingleGraphDataUnitImpl.execute(SingleGraphDataUnitImpl.java:40) [dataunit-sesame-impl-0.0.0.jar:na]
    at com.linkedpipes.plugin.transformer.sparql.construct.SparqlConstruct.execute(SparqlConstruct.java:42) [t-sparqlConstruct-0.0.0.jar:na]
    at com.linkedpipes.etl.executor.api.v1.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:281) [api-dpu-v1-impl-0.0.0.jar:na]
    at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:136) [executor.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

If possible, LP-ETL should raise a more specific exception that could help the user debug the pipeline.

Tested with the latest develop version (4f7687c71a8708c252155135ad7e409de5d2d775).

**Comment by skodape** [comment] 2016-05-19 15:12
@jindrichmynarz May I ask for the pipeline that cause this error?
A simple execution of 
```
CONSTRUCT { <http://localhost/resource>  <http://localhost/value> ?value } WHERE { 
BIND(RAND() AS ?value)
}
```
works fine.

**Comment by jindrichmynarz** [comment] 2016-05-19 15:22
See for example [this pipeline](https://gist.github.com/jindrichmynarz/8b56eae8bf1755abc139c6813eccb5c5).

**Comment by jindrichmynarz** [comment] 2016-05-19 15:25
It seems that Sesame/RDF4J doesn't support `ORDER BY RAND()`. However `BIND (RAND() AS ?rand) ` and `ORDER BY ?rand` works.

Nevertheless, this issue should not be read as a bug report for RDF4J. Instead, it is a enhancement proposal for better exceptions when an unsupported SPARQL function is used.

**Comment by skodape** [comment] 2016-05-19 15:54
It's not unsupported as 
```
SELECT ?s ?g WHERE { GRAPH ?g {?s a <http://plugins.linkedpipes.com/ontology/t-sparqlConstruct#Configuration> .} } ORDER BY RAND()
```
also works. The problem is in combination with the CONSTRUCT. 

Quick-fix can be to use BIND function and order property. Otherwise we can report this as a bug to RDF4J and wait for them to resolve the issue.

**Comment by jindrichmynarz** [comment] 2016-05-19 16:09
Yes, it seems to be a RDF4J bug, which is easy to work-around (e.g., using `BIND` as you suggest).

If all we get from RDF4J is `java.lang.NullPointerException`, then we can only report it as a bug. However, if RDF4J raises a more descriptive error, then LP-ETL can catch it and report that there is a problem with the query to the user.

**Comment by jakubklimek** [comment] 2017-05-27 07:02
@skodapetr Is there something more desriptive to be passed or did we report this to RDF4J (and therefore can link the issue and close this?)

**Comment by skodapetr** [comment] 2017-05-29 13:44
@jakubklimek  From RDF4J we got only NPE.  
This issue was reported as https://github.com/eclipse/rdf4j/issues/263

**Closed** 2017-05-30 09:37 UTC
Labels: bug
