### ISSUE TITLE
Updating component description has no effect

### ISSUE THREAD

**Issue by martinnec** [linkedpipes/etl#654] opened 2019-01-11 07:32 UTC
1) https://etl.skod.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.skod.opendata.cz%2Fresources%2Fpipelines%2F1547137017255

2) Change description of any component

3) Save

=> The description is not changed.

**Comment by jakubklimek** [comment] 2019-01-11 07:49
Duplicate of #648

**Closed by jakubklimek** 2019-01-11 07:49 UTC
