### ISSUE TITLE
Passing multiple configurations not supported in SPARQL SELECT component

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#176] opened 2016-06-10 15:23 UTC
When you pass SPARQL SELECT component multiple instances of `<http://plugins.linkedpipes.com/ontology/t-sparqlSelect#Configuration>` only one is used. This prevents generating multiple outputs, e.g., multiple CSV files output by the SPARQL SELECT component each for a single dataset contained in the input data.

I haven't tested if this is the case for other configurable components too (e.g., SPARQL CONSTRUCT), but it would be good to check their source code if they don't suffer from the same issue.

Tested with the latest develop version (0df73f420dd1277217992dcfe1243b312d0defb7).

**Comment by jakubklimek** [comment] 2016-06-10 15:32
This is by design. Do you have a use case where you actually need multiple generated queries and simply using multiple sparql component instances is not enough?

**Comment by jakubklimek** [comment] 2016-06-10 15:35
Also, the multiple config functionality is quite clear for SPARQL SELECT, but for other SPARQL components it is not clear what should be the result of such operation. A merged graph? Multiple graphs?

**Comment by jindrichmynarz** [comment] 2016-06-10 15:51
Yes, a use case is [converting DCV datasets to CSV](https://github.com/openbudgets/pipeline-fragments/tree/master/dcv/dcv-to-csv). Input may contain one or more instances of `qb:DataSet`, each of which should be converted to a CSV file.

I think the interpretation of multiple configurations is intuitive: simply execute the component for each configuration with the same input and combine the results into a list.

In case of SPARQL CONSTRUCT, when you have multiple configurations, then produce multiple RDF units. If necessary, these can be merged later by Graph Merger.

**Comment by jakubklimek** [comment] 2016-06-10 15:57
As there is no proper support for working with multiple graphs, I dont
think we will support this for RDF outputs now. But we can add support for
producing multiple CSV files from SPARQL SELECT.

**Comment by skodape** [comment] 2016-06-10 16:04
Note: Application of multiple configuration would also require synchronisation with the UI. As user may want to provide multiple CSV output files via the dialog.

We would then also need to explicitly state when the configuration from the input is used and when the configuration from the dialog is used. As in case of 1 : 1 (runtime : dialog ) configurations it easy to merge. But in case of n : 1 or n : n - I do not see an easy way.

Also when we start with this functionality we need to define, which component and why should support it. As we may also then want to apply multiple configuration for RdfToFiles (to produce ttl, trig) to ExcelToCsv (to process multiple sheets with different data), etc ... 

It may be better to provide some "flow control" components on the pipeline (like for each execution), to communicate this situation to the user.

**Comment by jindrichmynarz** [comment] 2016-06-10 16:27
Is it necessary to support the same functionality in the UI? If you provide the configuration manually, it's not a problem to create multiple instances of the component. However, if you generate the configuration automatically, then you cannot do that. I think that involving the UI would unnecessarily complicate the issue.

I think we can simply start with the SPARQL SELECT component, try it, and then port to other components if needed.

**Comment by jakubklimek** [comment] 2016-06-10 16:28
I would actually split it into two, the same as http get. One with dialog
and one without.

**Comment by jindrichmynarz** [comment] 2016-06-10 16:30
Why split? I don't see a reason why the UI needs to correspond one-to-one with the possibilities provided by generated configuration. I'm afraid that splitting each component into two would confuse users.

**Comment by jakubklimek** [comment] 2016-06-10 16:34
Typically, a component with a configuration in a dialog needs to support
templating in the future, which involves merging of configurations. It
would be harder to have multiple types of configurations on top of that.
There can be some shortcuts or filters for user later to distinguish
manually configurable components and components with generated
configuration.

**Comment by jindrichmynarz** [comment] 2016-06-10 16:36
> It would be harder to have multiple types of configurations on top of that.

There can be a single type of configuration: a list with 1 or more instances. This is a data structure that fits both manually provided configuration and generated configuration.

**Comment by jakubklimek** [comment] 2016-06-10 16:47
Still... it seems more confusing to me to have a component configurable both from the input and the dialog, especially if the expressiveness differs, than to have two components.

**Comment by jindrichmynarz** [comment] 2016-06-10 17:29
What would be an example situation in which it would be confusing?

I don't think this is something especially confusing. Many applications have functionality exposed via an API, that's not exposed via UI, e.g., Facebook.

**Comment by jakubklimek** [comment] 2016-06-17 10:12
Every time when a user reads in the documentation that the component supports something that is not covered by the dialog. We are still dealing with low level components that should be primarily clean from the developer point of view, a user friendly shortcuts can be done later.

**Comment by jindrichmynarz** [comment] 2016-06-17 10:46
I think it's perfectly fine to expose different functionality via the UI and via the API. I also assume the API has a separate documentation, so this feature can be documented only in it.

**Comment by jakubklimek** [comment] 2016-06-17 10:58
It is not exactly an API... it is just the RDF configuration accepted by the component, therefore it is documented in one place.

Also it is still not clear whether the dialog configuration should be merged with the rdf one, or replaced by it, etc.

I still think that two components are better. Nevertheless, I don't see either of the two options causing any serious problems, so let's do it this way and see later.

**Comment by jindrichmynarz** [comment] 2016-06-17 11:19
If there is configuration provided via a data unit, then it overrides the configuration in a component's dialog. I think (correct me if I'm wrong) this is the way how it's done at the moment.

**Comment by jakubklimek** [comment] 2016-06-17 11:21
Yes, because it is the easiest way. But this may change in the future when we introduce merging of configurations.

**Closed** 2016-06-20 07:28 UTC
Labels: enhancement
